on: 
  pull_request:

jobs:
  pr_lint:
    runs-on: ubuntu-22.04
    name: PR lint
    steps:
      - name: Custom PR linter
        id: pr-lint
        uses: ian-cawood/custom-pr-linter@v0.0

  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15
      - run: npm ci
      - run: npm test
